2024-10-29 01:04:08 - INFO - __main__ - Initializing training script
2024-10-29 01:04:08 - INFO - __main__ - Loading dataset...
Traceback (most recent call last):
  File "train.py", line 60, in <module>
    train_dataset, eval_dataset = get_dataset(training_args, sep_token="[SEP]")
  File "C:\Users\18519\Desktop\2024F NLP-DL\HWs\HW2\task2\task1\dataHelper.py", line 164, in get_dataset
    'train': train_dataset,
UnboundLocalError: local variable 'train_dataset' referenced before assignment
Traceback (most recent call last):
  File "train.py", line 60, in <module>
    train_dataset, eval_dataset = get_dataset(training_args, sep_token="[SEP]")
  File "C:\Users\18519\Desktop\2024F NLP-DL\HWs\HW2\task2\task1\dataHelper.py", line 164, in get_dataset
    'train': train_dataset,
UnboundLocalError: local variable 'train_dataset' referenced before assignment
